@auth = Bearer {{login.response.body.access_token}}

# @name login
POST {{apiUrl}}/auth/login
Content-Type: application/json

{
  //"email": "{{email}}",
  //"email": "admin@email.com",
  //"email": "editor@email.com",
  "email": "reader@email.com",
  //"email": "writer@email.com",
  "password": "{{password}}"
}
###

# @name profile
GET {{apiUrl}}/users/me
Authorization: {{auth}}
###

# @name createUser
POST {{apiUrl}}/users
Content-Type: application/json
Authorization: {{auth}}

{
  "name": "John Doe",
  "email": "john.doe@email.com",
  "password": "{{password}}"
}
###

GET {{apiUrl}}/users
Authorization: {{auth}}
###

GET {{apiUrl}}/users/{{createUser.response.body.id}}
Authorization: {{auth}}
###

PATCH {{apiUrl}}/users/{{createUser.response.body.id}}
Content-Type: application/json
Authorization: {{auth}}

{
  "role": "ADMIN"
}
###

DELETE {{apiUrl}}/users/{{createUser.response.body.id}}
Authorization: {{auth}}
###

# @name createPost
POST {{apiUrl}}/posts
Content-Type: application/json
Authorization: {{auth}}

{
  "title": "My First Post",
  "content": "This is my first post",
  "published": true
}
###

# @name getPosts
GET {{apiUrl}}/posts
Authorization: {{auth}}
###

# @name getPost
GET {{apiUrl}}/posts/{{createPost.response.body.id}}
Authorization: {{auth}}
###

# @name updatePost
PATCH {{apiUrl}}/posts/{{createPost.response.body.id}}
Content-Type: application/json
Authorization: {{auth}}

{
  "title": "My First Post Updated"
}
###

# @name deletePost
DELETE {{apiUrl}}/posts/{{createPost.response.body.id}}
Authorization: {{auth}}
###
