@auth = Bearer {{login.response.body.access_token}}

# @name login
POST {{apiUrl}}/auth/login
Content-Type: application/json

{
  //"email": "{{email}}",
  //"email": "admin@email.com",
  //"email": "editor@email.com",
  //"email": "writer@email.com",
  //"email": "reader@email.com",
  "email": "writer-with-custom-permissions@email.com",
  "password": "{{password}}"
}
###

# @name profile
GET {{apiUrl}}/users/me
Authorization: {{auth}}
###

# @name createUser
POST {{apiUrl}}/users
Content-Type: application/json
Authorization: {{auth}}

{
  "name": "Writer With Custom Permissions",
  "email": "writer-with-custom-permissions@email.com",
  "password": "{{password}}",
  "role": "WRITER",
  "permissions": [
    {
      "action": "read",
      "resource": "User"
    }
  ]
}
###

GET {{apiUrl}}/users
Authorization: {{auth}}
###

GET {{apiUrl}}/users/{{createUser.response.body.id}}
Authorization: {{auth}}
###

PATCH {{apiUrl}}/users/{{createUser.response.body.id}}
Content-Type: application/json
Authorization: {{auth}}

{
  "role": "ADMIN"
}
###

DELETE {{apiUrl}}/users/{{createUser.response.body.id}}
Authorization: {{auth}}
###

# @name createPost
POST {{apiUrl}}/posts
Content-Type: application/json
Authorization: {{auth}}

{
  "title": "Post 4",
  "content": "This is the post 4",
  "published": false
}
###

# @name getPosts
GET {{apiUrl}}/posts
Authorization: {{auth}}
###

# @name getPost
GET {{apiUrl}}/posts/cm999fc8r0005v7s8cc8khmf3
Authorization: {{auth}}
###

# @name updatePost
PATCH {{apiUrl}}/posts/{{createPost.response.body.id}}
Content-Type: application/json
Authorization: {{auth}}

{
  "title": "Post 4 Updated"
}
###

# @name deletePost
DELETE {{apiUrl}}/posts/{{createPost.response.body.id}}
Authorization: {{auth}}
###
